name: Build and Release Youtue EXE on Merge

on:
  push:
    branches:
      - master

permissions:
  contents: write     # 릴리즈 작성/태그 생성 권한 부여
  issues: read
  pull-requests: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 모든 커밋 필요 (semantic 분석용)

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install python-semantic-release pyinstaller

      - name: Download ffmpeg
        run: |
          Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg
          move ffmpeg\*\bin\ffmpeg.exe ffmpeg\
        shell: pwsh

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: semantic_release:*
        run: |
          semantic-release publish