name: Build and Release Youtue EXE on Merge

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download ffmpeg
        run: |
          Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg
          move ffmpeg\*\bin\ffmpeg.exe ffmpeg\
        shell: pwsh

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed ^
            --add-binary "ffmpeg\\ffmpeg.exe;." ^
            --name "Youtue" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Youtue-exe
          path: dist/Youtue.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: Youtue-exe
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}  # 자동 증가 버전
          name: "Youtue Build #${{ github.run_number }}"
          body: "자동 빌드된 실행 파일입니다 (main merge 기준)."
          files: YouTubeDownloader.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}